# Generated by Django 4.0.10 on 2023-08-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_cluster_channel'),
        ('cluster', '0003_clusterevent_eventattendance_clusterevent_attendees_and_more'),
    ]

    operations = [
    ]
