# Generated by Django 4.0.10 on 2023-08-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_cluster_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='channel',
        ),
    ]
