# Generated by Django 4.0.10 on 2023-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessagemodel",
            name="esp",
            field=models.CharField(
                choices=[(0, "SendInBlue"), (1, "SendGrid")], default=0, max_length=100
            ),
        ),
    ]
