# Generated by Django 4.0.10 on 2023-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('new_follower_event', 'New follower event'), ('unfollow_event', 'Unfollow event')], max_length=50),
        ),
    ]
