# Generated by Django 4.0.10 on 2023-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notificationmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[(1, 'Recieved Cluster invitation'), (2, 'Cancelled Cluster Invitation'), (3, 'Accepted Cluster Invitation'), (4, 'Rejected Cluster Invitation')], max_length=50),
        ),
    ]
