FACULTY_CHOICES = (
    ('Agriculture and Forestry', 'Faculty of Agriculture and Forestry'),
    ('Arts', 'Faculty of Arts'),
    ('College of Medicine', 'College of Medicine'),
    ('Economics and Management Sciences', 'Faculty of Economics and Management Sciences'),
    ('Education', 'Faculty of Education'),
    ('Environmental Design and Management', 'Faculty of Environmental Design and Management'),
    ('Law', 'Faculty of Law'),
    ('Multidisciplinary Studies', 'Faculty of Multidisciplinary Studies'),
    ('Pharmacy', 'Faculty of Pharmacy'),
    ('Renewable Natural Resources', 'Faculty of Renewable Natural Resources'),
    ('Science', 'Faculty of Science'),
    ('Social Sciences', 'Faculty of Social Sciences'),
    ('Technology', 'Faculty of Technology'),
    ('Veterinary Medicine', 'Faculty of Veterinary Medicine'),
)

DEPARTMENT_CHOICES = [
    ('Agricultural Economics', 'Department of Agricultural Economics'),
    ('Agricultural Extension and Rural Development', 'Department of Agricultural Extension and Rural Development'),
    ('Agronomy', 'Department of Agronomy'),
    ('Animal Science', 'Department of Animal Science'),
    ('Crop Protection and Environmental Biology', 'Department of Crop Protection and Environmental Biology'),
    ('Forest Resources Management', 'Department of Forest Resources Management'),
    ('Arabic and Islamic Studies', 'Department of Arabic and Islamic Studies'),
    ('Archaeology and Anthropology', 'Department of Archaeology and Anthropology'),
    ('Classics', 'Department of Classics'),
    ('Communication and Language Arts', 'Department of Communication and Language Arts'),
    ('English Language and Literature', 'Department of English Language and Literature'),
    ('European Studies - French', 'Department of European Studies - French'),
    ('European Studies - German', 'Department of European Studies - German'),
    ('European Studies - Russian', 'Department of European Studies - Russian'),
    ('History', 'Department of History'),
    ('Linguistics and African Languages', 'Department of Linguistics and African Languages'),
    ('Music', 'Department of Music'),
    ('Philosophy', 'Department of Philosophy'),
    ('Religious Studies', 'Department of Religious Studies'),
    ('Theatre Arts and Film Studies', 'Department of Theatre Arts and Film Studies'),
    ('Yoruba', 'Department of Yoruba'),
    ('Arts and Social Science Education', 'Department of Arts and Social Science Education'),
    ('Early Childhood Education', 'Department of Early Childhood Education'),
    ('Educational Management', 'Department of Educational Management'),
    ('Guidance and Counselling', 'Department of Guidance and Counselling'),
    ('Human Kinetics and Health Education', 'Department of Human Kinetics and Health Education'),
    ('Science and Technology Education', 'Department of Science and Technology Education'),
    ('Commercial and Industrial Law', 'Department of Commercial and Industrial Law'),
    ('Jurisprudence and International Law', 'Department of Jurisprudence and International Law'),
    ('Private and Property Law', 'Department of Private and Property Law'),
    ('Public Law', 'Department of Public Law'),
    ('Pharmaceutical Chemistry', 'Department of Pharmaceutical Chemistry'),
    ('Pharmacognosy', 'Department of Pharmacognosy'),
    ('Pharmacology and Therapeutics', 'Department of Pharmacology and Therapeutics'),
    ('Pharmacy', 'Department of Pharmacy'),
    ('Ecotourism and Environmental Management', 'Department of Ecotourism and Environmental Management'),
    ('Fisheries and Wildlife Management', 'Department of Fisheries and Wildlife Management'),
    ('Anthropology', 'Department of Anthropology'),
    ('Archaeology', 'Department of Archaeology'),
    ('Botany', 'Department of Botany'),
    ('Chemistry', 'Department of Chemistry'),
    ('Computer Science', 'Department of Computer Science'),
    ('Geography', 'Department of Geography'),
    ('Geology', 'Department of Geology'),
    ('Mathematics', 'Department of Mathematics'),
    ('Microbiology', 'Department of Microbiology'),
    ('Physics', 'Department of Physics'),
    ('Statistics', 'Department of Statistics'),
    ('Zoology', 'Department of Zoology'),
    ('Economics', 'Department of Economics'),
    ('Political Science', 'Department of Political Science'),
    ('Psychology', 'Department of Psychology'),
    ('Sociology', 'Department of Sociology'),
    ('Agricultural and Environmental Engineering', 'Department of Agricultural and Environmental Engineering'),
    ('Civil Engineering', 'Department of Civil Engineering'),
    ('Electrical and Electronics Engineering', 'Department of Electrical and Electronics Engineering'),
    ('Industrial and Production Engineering', 'Department of Industrial and Production Engineering'),
    ('Mechanical Engineering', 'Department of Mechanical Engineering'),
    ('Petroleum Engineering', 'Department of Petroleum Engineering'),
    ('Theriogenology and Production', 'Department of Theriogenology and Production'),
    ('Veterinary Anatomy', 'Department of Veterinary Anatomy'),
    ('Veterinary Medicine', 'Department of Veterinary Medicine'),
    ('Veterinary Microbiology', 'Department of Veterinary Microbiology'),
    ('Veterinary Parasitology and Entomology', 'Department of Veterinary Parasitology and Entomology'),
    ('Veterinary Pathology', 'Department of Veterinary Pathology'),
    ('Veterinary Physiology, Biochemistry and Pharmacology',
     'Department of Veterinary Physiology, Biochemistry and Pharmacology'),
    ('Veterinary Public Health and Preventive Medicine', 'Department of Veterinary Public Health and Preventive Medicine'),
    ('Veterinary Surgery and Radiology', 'Department of Veterinary Surgery and Radiology'),
    ('Anatomy', 'Department of Anatomy'),
    ('Biochemistry', 'Department of Biochemistry'),
    ('Chemical Pathology', 'Department of Chemical Pathology'),
    ('Haematology and Blood Transfusion', 'Department of Haematology and Blood Transfusion'),
    ('Medical Microbiology and Parasitology', 'Department of Medical Microbiology and Parasitology'),
    ('Pharmacology and Therapeutics', 'Department of Pharmacology and Therapeutics'),
    ('Physiology', 'Department of Physiology'),
    ('Family Medicine', 'Department of Family Medicine'),
    ('Mental Health', 'Department of Mental Health'),
    ('Ophthalmology', 'Department of Ophthalmology'),
    ('Paediatrics', 'Department of Paediatrics'),
    ('Radiology', 'Department of Radiology'),
    ('Surgery', 'Department of Surgery'),
    ('Anaesthesia', 'Department of Anaesthesia'),
    ('Dermatology', 'Department of Dermatology and Venereology'),
    ('Medical Rehabilitation', 'Department of Medical Rehabilitation'),
    ('Nursing', 'Department of Nursing'),
    ('Community Medicine', 'Department of Community Medicine'),
    ('Health Policy and Management', 'Department of Health Policy and Management'),
    ('Human Nutrition', 'Department of Human Nutrition'),
    ('Physiotherapy', 'Department of Physiotherapy'),
    ('Radiotherapy', 'Department of Radiotherapy'),
    ('Epidemiology, Medical Statistics and Environmental Health (EMSEH)',
     'Department of Epidemiology, Medical Statistics and Environmental Health (EMSEH)'),
    ('Health Policy and Management', 'Department of Health Policy and Management'),
    ('Health Promotion and Education', 'Department of Health Promotion and Education'),
    ('Institute of Advanced Medical Research and Training', 'Institute of Advanced Medical Research and Training'),
    ('Medicine', 'Department of Medicine'),
    ('Obstetrics and Gynaecology', 'Department of Obstetrics and Gynaecology'),
    ('Physiology', 'Department of Physiology'),
    ('Preventive Medicine and Primary Care', 'Department of Preventive Medicine and Primary Care'),
    ('Psychiatry', 'Department of Psychiatry'),
    ('Architecture', 'Department of Architecture'),
    ('Estate Management', 'Department of Estate Management'),
    ('Urban and Regional Planning', 'Department of Urban and Regional Planning'),
    ('Quantity Surveying', 'Department of Quantity Surveying'),
    ('Forest Production and Products', 'Department of Forest Production and Products'),
    ('Aquaculture and Fisheries Management', 'Department of Aquaculture and Fisheries Management'),
    ('Social and Environmental Forestry', 'Department of Wildlife and Ecotourism Management'),
    ('Wildlife and Fisheries Management', 'Department of Wildlife and Fisheries Management'),
    ('Peace, Security and Humanitarian Studies', 'Department of Peace, Security and Humanitarian Studies'),
    ('Mineral, Petroleum, Energy, Economic and Law', 'Department of Mineral, Petroleum, Energy, Economic and Law'),
    ('Data and Information Science', 'Department of Data and Information Science'),
    ('Sustainability Studies', 'Department of Sustainability Studies'),
    ('Institute of African studies', 'Institute of African studies'),
]
