# Generated by Django 4.0.10 on 2023-04-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_valid',
            new_name='is_active',
        ),
    ]
