# Generated by Django 4.0.10 on 2023-06-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_follows_customuser_follows_follows_user_from_and_more'),
        ('accounts', '0003_friendship_friendshipinvitation_and_more'),
    ]

    operations = [
    ]
