# Generated by Django 4.0.10 on 2023-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userhandle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHandle',
        ),
    ]
