# Generated by Django 4.0.10 on 2023-08-23 10:44

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uia_backend.libs.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_follows_customuser_follows_follows_user_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenericSettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last update at')),
                ('notification', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[uia_backend.libs.validators.validate_settings_notification])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
