# Generated by Django 4.0.10 on 2023-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_follows_customuser_follows_follows_user_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=255),
        ),
    ]
