MIN_ALLOWED_GRADUATION_YEAR = "1948"

EMAIL_VERIFICATION_ACTIVE_PERIOD = (
    24  # how long a email verification mail should last in hours before expiration
)

EMAIL_VERIFICATION_TEMPLATE_ID = ""

OTP_CHARACTER_LENGTH = 4
OTP_ACTIVE_PERIOD = 30
FORGET_PASSWORD_TEMPLATE_ID = ""
