MIN_ALLOWED_GRADUATION_YEAR = "1948"

# how long an email verification mail should last in hours before expiration
EMAIL_VERIFICATION_ACTIVE_PERIOD = 24

# how long a password reset otp should last in minutes before expiration
PASSWORD_RESET_ACTIVE_PERIOD = 10
PASSWORD_RESET_OTP_LENGTH = 6

# NOTE :Joseph you need to find a better way to sort email templates for cases where we need to switch ESPs
EMAIL_VERIFICATION_TEMPLATE_ID = "d-1dda679ebf2846b498b6ab027a4f73b7"
PASSWORD_CHANGE_TEMPLATE_ID = "d-7cdf816164d64d0791b9b0b6f9a7ffff"
PASSWORD_RESET_TEMPLATE_ID = "d-3a50ac41a1654b548f8521e1ae40bad4"

# This is for creating or updating user handle
HANDLE_CREATION = "handle-creation"
HANDLE_UPDATE = "handle-update"
CACHE_DURATION = 3600

FACULTY_CHOICES = [
    "Agriculture and Forestry",
    "Arts",
    "Medicine",
    "Economics and Management Sciences",
    "Education",
    "Environmental Design and Management",
    "Law",
    "Multidisciplinary Studies",
    "Pharmacy",
    "Renewable Natural Resources",
    "Science",
    "Social Sciences",
    "Technology",
    "Veterinary Medicine",
]

DEPARTMENT_CHOICES = [
    "Agricultural Economics",
    "Agricultural Extension and Rural Development",
    "Agronomy",
    "Animal Science",
    "Protection and Environmental Biology",
    "Forest Resources Management",
    "Arabic and Islamic Studies",
    "Archaeology and Anthropology",
    "Classics",
    "Communication and Language Arts",
    "English Language and Literature",
    "European Studies - French",
    "European Studies - German",
    "European Studies - Russian",
    "History",
    "Linguistics and African Languages",
    "Music",
    "Philosophy",
    "Religious Studies",
    "Theatre Arts and Film Studies",
    "Yoruba",
    "Arts and Social Science Education",
    "Early Childhood Education",
    "Educational Management",
    "Guidance and Counselling",
    "Human Kinetics and Health Education",
    "Science and Technology Education",
    "Commercial and Industrial Law",
    "Jurisprudence and International Law",
    "Private and Property Law",
    "Public Law",
    "Pharmaceutical Chemistry",
    "Pharmacognosy",
    "Pharmacology and Therapeutics",
    "Pharmacy",
    "Ecotourism and Environmental Management",
    "Fisheries and Wildlife Management",
    "Anthropology",
    "Archaeology",
    "Botany",
    "Chemistry",
    "Computer Science",
    "Geography",
    "Geology",
    "Mathematics",
    "Microbiology",
    "Physics",
    "Statistics",
    "Zoology",
    "Economics",
    "Political Science",
    "Psychology",
    "Sociology",
    "Agricultural and Environmental Engineering",
    "Civil Engineering",
    "Electrical and Electronics Engineering",
    "Industrial and Production Engineering",
    "Mechanical Engineering",
    "Petroleum Engineering",
    "Theriogenology and Production",
    "Veterinary Anatomy",
    "Veterinary Medicine",
    "Veterinary Microbiology",
    "Veterinary Parasitology and Entomology",
    "Veterinary Pathology",
    "Veterinary Physiology, Biochemistry and Pharmacology",
    "Veterinary Public Health and Preventive Medicine",
    "Veterinary Surgery and Radiology",
    "Anatomy",
    "Biochemistry",
    "Chemical Pathology",
    "Haematology and Blood Transfusion",
    "Medical Microbiology and Parasitology",
    "Pharmacology and Therapeutics",
    "Physiology",
    "Family Medicine",
    "Mental Health",
    "Ophthalmology",
    "Paediatrics",
    "Radiology",
    "Surgery",
    "Anaesthesia",
    "Dermatology and Venereology",
    "Medical Rehabilitation",
    "Nursing",
    "Community Medicine",
    "Health Policy and Management",
    "Human Nutrition",
    "Physiotherapy",
    "Radiotherapy",
    "Epidemiology, Medical Statistics and Environmental Health (EMSEH)",
    "Health Policy and Management",
    "Health Promotion and Education",
    "Advanced Medical Research and Training",
    "Medicine",
    "Obstetrics and Gynaecology",
    "Physiology",
    "Preventive Medicine and Primary Care",
    "Psychiatry",
    "Architecture",
    "Estate Management",
    "Urban and Regional Planning",
    "Quantity Surveying",
    "Forest Production and Products",
    "Aquaculture and Fisheries Management",
    "Wildlife and Ecotourism Management",
    "Wildlife and Fisheries Management",
    "Peace, Security and Humanitarian Studies",
    "Mineral, Petroleum, Energy, Economic and Law",
    "Data and Information Science",
    "Sustainability Studies",
    "Institute of African studies",
]
